export type ProgrammingLanguage =
    | 'TypeScript'
    | 'JavaScript'
    | 'Python'
    | 'Java'
    | 'C#'
    | 'C++'
    | 'PHP'
    | 'Kotlin'
    | 'Assembly'
    | 'C'
    | 'Vue'
    | 'React'
    | 'Angular'
    | 'Bash'
